Changes to get solvers working
Few changes to keep up with Louis changes. Working: AdvDiff_swarm, Darcy, Stokes.

Not Working:
- *Adv_diff*:

-> 1205 self._F_star_projection_solver.solve()
   1207 with self._nswarm_F.access(nX0):
   1208     nX0.data[...] = self._nswarm_F.data[...]
ValueError: could not broadcast input array from shape (33282,) into shape (73728,)

Notes:
- Had to update BC in workflow, issue with int64 (python) and long (petsc) np array on mac. Had to set np array to int32.
- Have to set each BC individually